- hosts: 127.0.0.1
  connection: local
  become: yes
  vars_files:
    - 02-license-registercm_vars.yml
    - /ks/license_vars.yml
    
  tasks:
    - name: Add NSX License
      nsxt_licenses:
          hostname: "{{ nsx_node1.mgmt_ip }}"
          username: "{{ nsx_username }}"
          password: "{{ nsx_password }}"
          validate_certs: "{{ validate_certs }}"
          license_key: "{{ license_key }}"
          state: "{{ state }}"


    - name: Register compute manager
      nsxt_fabric_compute_managers:
          hostname: "{{ nsx_node1.mgmt_ip }}"
          username: "{{ nsx_username }}"
          password: "{{ nsx_password }}"
          validate_certs: "{{ validate_certs }}"
          display_name: "{{ item.display_name }}"
          server: "{{ item.mgmt_ip }}"
          origin_type: "{{ item.origin_type }}"
          credential:
            credential_type: "{{ item.credential_type }}"
            username: "{{ item.username }}"
            password: "{{ item.password }}"
          state: present
      with_items:
        - "{{compute_managers}}"   