# Copyright 2018 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause OR GPL-3.0-only
---
- hosts: nsxtmgrs
  connection: local
  vars_files:
    - setup_infra_vars.yml
    - 04_setup_TEP_IP_Pools_vars.yml
  tasks:
    - name: Create IP Pools
      vmware.ansible_for_nsxt.nsxt_policy_ip_pool:
        hostname: "{{ nsx_node1.mgmt_ip }}"
        username: "{{ nsx_username }}"
        password: "{{ nsx_password }}"
        validate_certs: "{{ validate_certs }}"
        display_name: "{{ item.display_name }}"
        pool_static_subnets: "{{ item.pool_static_subnets }}"
        state: "{{ state }}"
      with_items:
        - "{{ ip_pools  }}"
