# Copyright 2018 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause OR GPL-3.0-only
---
- hosts: nsxtmgrs
  connection: local
  vars_files:
    - setup_infra_vars.yml
    - 06_setup_transport_node_profiles_vars.yml
  tasks:
    - name: Create Transport Node Profiles
      nsxt_transport_node_profiles:
        hostname: "{{nsx_node1.mgmt_ip}}"
        username: "{{ nsx_username }}"
        password: "{{ nsx_password }}"
        validate_certs: "{{ validate_certs }}"
        resource_type: TransportNodeProfile
        display_name: "{{ item.display_name }}"
        description: "{{ item.description }}"
        host_switch_spec:
          resource_type: StandardHostSwitchSpec
          host_switches: "{{ item.host_switches }}"
        transport_zone_endpoints: "{{ item.transport_zone_endpoints }}"
        state: "{{ state }}"
      with_items:
        - "{{ transport_node_profiles }}"
