---
#before you can do all this, you need to make sure the following:
# 1. nsxt mgr services is up and running
# 2. st en, vi /etc/ssh/sshd_config, PermitRootLogin yes, systemctl restart sshd
# 3. to understand all the options available, look at the corrosponding .py files in modules
- name: Install All NSX-T Licenses
  nsxt_licenses:
    hostname: "{{ nsx_ip_0 }}"
    username: "admin"
    password: "{{nsx_cli_passwd_0}}"
    validate_certs: no
    license_key: "xxxxx-0NM02-883DR-0HNH2-xxxxx"
    state: present
  ignore_errors: yes  # If license in already in use or not applicable, it will result in 'failure', so need to ensure we continue by ignoring the error

- name: Register compute manager with NSX
  nsxt_fabric_compute_managers:
    hostname: "{{ nsx_ip_0 }}"
    username: "admin"
    password: "{{nsx_cli_passwd_0}}"
    validate_certs: False
    display_name: "{{item.display_name}}"
    server: "{{item.server}}"
    origin_type: vCenter
    credential:
      credential_type: "UsernamePasswordLoginCredential"
      username: "administrator@vsphere.local"
      password: "VMware1!"
    state: present
  loop:
    # - { display_name: 'NSXT-vCenter130', server: '192.168.254.130' }
    # - { display_name: 'NSXV-vCenter131', server: '192.168.254.131' }
     - { display_name: '192.168.254.132', server: '192.168.254.132' }
    
  ignore_errors: yes  



