---
#before you can do all this, you need to make sure the following:
# 1. nsxt mgr services is up and running
# 2. st en, vi /etc/ssh/sshd_config, PermitRootLogin yes, systemctl restart sshd
# 3. to understand all the options available, look at the corrosponding .py files in modules
- name: Install All NSX-T Licenses
  nsxt_licenses:
    hostname: "{{ nsx_mgr_ip }}"
    username: "admin"
    password: "{{nsx_cli_passwd_0}}"
    validate_certs: no
    license_key: "A56CM-0NM02-883DR-0HNH2-88NM5"
    state: present
  ignore_errors: yes  # If license in already in use or not applicable, it will result in 'failure', so need to ensure we continue by ignoring the error

- name: Register compute manager with NSX
  nsxt_fabric_compute_managers:
    hostname: "{{ nsx_mgr_ip }}"
    username: "admin"
    password: "{{nsx_cli_passwd_0}}"
    validate_certs: False
    display_name: "vCenter131"
    server: "{{compute_mgr}}"
    description: "Description of the resource"
    origin_type: vCenter
    credential:
      credential_type: "UsernamePasswordLoginCredential"
      username: "administrator@vsphere.local"
      password: "VMware1!"
    state: present
  ignore_errors: yes  

- name: Create NSX-T transport zones
  nsxt_transport_zones:
    hostname: "{{ nsx_mgr_ip }}"
    username: "admin"
    password: "{{ nsx_cli_passwd_0 }}"
    validate_certs: False
    resource_type: "TransportZone"
    display_name: "overlah tz"
    is_default: "true"
    transport_type: "OVERLAY"
    host_switch_name: "vdsdata"
    host_switch_mode: "STANDARD"
    state: "present"
  ignore_errors: yes  



