---

- name: Install All NSX-T Licenses
    nsxt_licenses:
      hostname: "{{ nsx_mgr_ip }}"
      username: "{{ admin }}"
      password: "{{ nsx_cli_passwd_0 }}"
      validate_certs: no
      license_key: "A56CM-0NM02-883DR-0HNH2-88NM5"
      state: present
