---
all:
  children:
    managers:
    edges:
  vars:
    vcenter: 'vc01.home.lab'
    vcenter_user: 'administrator@lab.home'
    vcenter_password: 'VMware1!VMware1!'
    vcenter_datacenter: 'DC-2'
    vcenter_folder: '/Ansible'
    vcenter_cluster: 'management'
    vcenter_datastore: 'remote-install-location'
    nsx_mgmt: 'dvs-mgmt'
    nsx_edge_fp : 'dvs-trunk'
    manager_ova: "/Users/nmammadov/Downloads/OVAISO/nsx-unified-appliance-3.0.0.0.0.15946739.ova"
    edge_ova: "/Users/nmammadov/Downloads/OVAISO/nsx-edge-3.0.0.0.0.15946012.ova"
    nsx_passwd_0 : "VMware1!VMware1!"
    nsx_cli_passwd_0 : "VMware1!VMware1!"
    nsx_cli_audit_passwd_0 : "VMware1!VMware1!"
    nsx_gateway_0 : "172.23.10.252"
    nsx_netmask_0 : "255.255.255.0"
    nsx_dns1_0 : "192.168.156.11"
    nsx_domain_0 : "home.lab"
    nsx_ntp_0 : "192.168.156.11"
    nsx_isSSHEnabled : "True"

managers:
  hosts:
    nsxmanager101.home.lab: 
      nsx_mgr_ip : '172.23.10.61' 
edges:
  hosts:
    nsxedge101.home.lab:
      nsx_edge_ip: '172.23.10.64' 
    nsxedge102.home.lab:
      nsx_edge_ip: '172.23.10.65'

