---
# - name : Deploy NSX Manager OVA
#   community.vmware.vmware_deploy_ovf:
#       hostname: '{{ vcenter }}'
#       username: '{{ vcenter_user }}'
#       password: '{{ vcenter_password }}'
#       datacenter : '{{ vcenter_datacenter }}'
#       validate_certs: no
#       datastore : '{{ vcenter_datastore }}'
#       folder : '{{ vcenter_folder }}'
#       esxi_hostname : '{{ esxi_ip }}' #also must specify inventory file to work ansible-playbook -i hosts.yml
#       name : '{{ inventory_hostname_short }}'
#       disk_provisioning: thin
#       wait: false
#       networks: 
#         "Network 1": '{{ nsx_mgmt }}'
#       ovf: '{{ manager_ova }}'
#       wait_for_ip_address: false
#       inject_ovf_env: yes
#       properties:
#           nsx_passwd_0 : '{{ nsx_passwd_0 }}'
#           nsx_cli_passwd_0 : '{{ nsx_cli_passwd_0 }}'
#           nsx_cli_audit_passwd_0 : '{{ nsx_cli_audit_passwd_0 }}'
#           nsx_hostname : '{{ inventory_hostname }}'
#           nsx_gateway_0 : '{{ nsx_gateway_0 }}'
#           nsx_ip_0 : '{{ nsx_mgr_ip }}'
#           nsx_netmask_0 : '{{ nsx_netmask_0 }}'
#           nsx_dns1_0 : '{{ nsx_dns1_0 }}'
#           nsx_domain_0 : '{{ nsx_domain_0 }}'
#           nsx_ntp_0 : '{{ nsx_ntp_0 }}'
#           nsx_isSSHEnabled : '{{ nsx_isSSHEnabled }}'
#   delegate_to : localhost


- name: Shows status of nsxt manager
  nsxt_manager_status:
      hostname: "nsx_mgr_ip"
      username: "admin"
      password: "nsx_passwd_0"
      validate_certs: False
      wait_time: 50
  delegate_to : localhost


# - name: Install All NSX-T Licenses
#     nsxt_licenses:
#       hostname: "{{ nsx_mgr_ip }}"
#       username: "{{ admin }}"
#       password: "{{ nsx_cli_passwd_0 }}"
#       validate_certs: no
#       license_key: "{{ item.KeyCode }}"
#       state: present
#     loop: "{{ License.VMware.NSXT.Licenses | default([]) }}"
#     ignore_errors: yes                                                             # If license in already in use or not applicable, it will result in 'failure', so need to ensure we continue by ignoring the error
#     no_log: true