---
- name: deploy NSX Manager OVA
  nsxt_deploy_ova:  
    ovftool_path: "/usr/bin"
    datacenter: "{{ vcenter_datacenter }}"
    datastore: "{{ vcenter_datastore }}"
    portgroup: "{{ nsx_mgmt }}"
    cluster: "{{ vcenter_cluster }}"
    vmname: "{{  inventory_hostname }}"
    hostname: "{{  inventory_hostname }}"
    dns_server: "{{ nsx_dns1_0 }}"
    dns_domain: "{{ nsx_domain_0 }}"
    ntp_server: "{{ nsx_ntp_0 }}"
    gateway: "{{ nsx_gateway_0 }}"
    ip_address: "{{ nsx_mgr_ip }}"
    netmask: "{{ nsx_netmask_0 }}"
    admin_password: "{{ nsx_passwd_0 }}"
    cli_password: "{{ nsx_passwd_0 }}"
    path_to_ova: "{{ path_to_ova }}"
    ova_file: "{{ manager_ova }}"
    vcenter: "{{ vcenter }}"
    vcenter_user: "{{ vcenter_user }}"
    vcenter_passwd: "{{ vcenter_password }}"
    deployment_size: "small"
    role: "nsx-manager nsx-controller"
  delegate_to: localhost
- name: Check manager status
  nsxt_manager_status:
      hostname: "{{ nsx_mgr_ip }}"
      username: "admin"
      password: "{{ nsx_passwd_0 }}"
      validate_certs: false
      wait_time: 50
