all:
  children:
    nsxtmgrs:
    nsxtedges:
    ext_net:
    nsxvmgrs:

  vars:
    vcenter: '192.168.254.133'
    vcenter_user: 'administrator@vsphere.local'
    vcenter_password: 'VMware1!'
    vcenter_datacenter: 'dc1'
    vcenter_folder: '/Ansible'
    vcenter_cluster: 'NSXT-EDGECLUSTER'
    vcenter_datastore: 'iscsi108'
    nsx_mgmt: 'VM Network'
    nsx_edge_fp : 'isolated-trunk'
    manager_ova: "/ks/iso/nsx-unified-appliance-3.1.2.1.0.17975796.ova"
    edge_ova: "/ks/iso/nsx-edge-3.1.2.1.0.17975773.ova"
    nsx_passwd_0 : "VMware1!VMware1!"
    nsx_cli_passwd_0 : "VMware1!VMware1!"
    nsx_cli_audit_passwd_0 : "VMware1!VMware1!"
    nsx_gateway_0 : "192.168.254.254"
    nsx_netmask_0 : "255.255.0.0"
    nsx_dns1_0 : "192.168.254.123"
    nsx_domain_0 : "rubber.ducky"
    nsx_ntp_0 : "time.google.com"
    nsx_isSSHEnabled : "True"

nsxtmgrs:
  hosts:
    0nsxtmgr.rubber.ducky: 
      nsx_mgr_ip : '192.168.254.61' 
nsxtedges:
  hosts:
    0nsxedge64.rubber.ducky:
      nsx_edge_ip: '192.168.254.64' 
    0nsxedge65.rubber.ducky:
      nsx_edge_ip: '192.168.254.65'
ext_net:
  hosts:
    0rtr1:
    0rtr2:
nsxvmgrs:
  hosts:
    0nsxvmgr01:
    
