edge_transport_nodes:
- display_name: TN1
  host_switches:
  - host_switch_profiles:
    - name: uplinkProfile1
      type: UplinkHostSwitchProfile
    host_switch_name: hostswitch1
    host_switch_mode: STANDARD
    pnics:
    - device_name: "vmnic1"
      uplink_name: "uplink-1"
    ip_assignment_spec:
      resource_type: StaticIpPoolSpec
      ip_pool_name: "ippool1"
    transport_zone_endpoints:
    - transport_zone_name: "TZ1"
  transport_zone_endpoints:
  - transport_zone_name: "TZ1"
  node_deployment_info:
    resource_type: "EdgeNode"
    display_name: "EdegeNode1"
    ip_addresses:
    deployment_type: "VIRTUAL_MACHINE"
    deployment_config:
      form_factor: "SMALL"
      node_user_settings:
        cli_password: "Admin!23Admin"
        root_password: "Admin!23Admin"
      vm_deployment_config:
        placement_type: VsphereDeploymentConfig
        vc_name: "VC2"
        vc_username: "administrator@vsphere.local"
        vc_password:  "XYZ#@!"
        data_network:
        - VM Network
        - VM Network
        - VM Network
        management_network: "VM Network"
        hostname: "EdgeVM1"
        compute: "Cluster1"
        storage: "Datastore1"
        host: "MyHost"
        default_gateway_addresses: X.Y.Z.A
        management_port_subnets: P.Q.R.s/S