all:
  children:
    esxi:
#     nsxtmgrs:
#     # nsxtedges:
#     # ext_net:
#     nsxvmgrs:

#   vars:
#     vcenter: '192.168.254.133'
#     vcenter_user: 'administrator@vsphere.local'
   

# nsxtmgrs:
#   hosts:
    0nsxtmgr.rubber.ducky: 
      # nsx_mgr_ip : '192.168.254.61'
      # ansible_user: 'root' #requires that root be allowed to login, so much junk in this crap module
      # compute_mgr:  "192.168.254.131"

# nsxtedges:
#   hosts:
#     0nsxedge64.rubber.ducky:
#       nsx_edge_ip: '192.168.254.64' 
#     0nsxedge65.rubber.ducky:
#       nsx_edge_ip: '192.168.254.65'
# ext_net:
#   hosts:
#     0rtr1:
#     0rtr2:
nsxvmgrs:
  hosts:
    0nsxvmgr01: 
  
esxi:
  hosts:
    192.168.8.111:
      ansible_ssh_user: root
      ansible_ssh_pass: 'VMware1!'
      file: 'test.sh'
